site_name: Test docs
site_description: 'A docs test'
site_author: 'Michael Hausenblas'
docs_dir: docs/
repo_name: 'ayushdhar/canary-app'
repo_url: 'https://github.com/ayushdhar/canary-app'
nav:
    - Home: index.md
theme:
  name: 'material'