# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build_artifact.zip
          path: .
          retention-days: 1
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: build_artifact.zip
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2
      - name: synthesis
        run: npm run cdk synth -- -v -o dist
      - name: deploy
        run: npm run cdk deploy


